name: Publish Docker Image

on:
  push:
    branches:
      - main  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install all python dependencies
    - name: Install Python dependencies
      run: |
        make install

    - name: Run DVC pipeline
      run: |
        dvc repro

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: 'Opsifygit'
        password: 'dckr_pat_F0i_Enaei105Kv7NhgMPtgwqUCQ'
        
    - name: Build Flask app
      run: |
        docker build . --file ./app/Dockerfile --tag opsifygit/project:latest
    - name: Publish Container
      run: |
        docker push opsifygit/project:latest
